### PR TITLE
1.4

### LINKED ISSUE #45: [Suggestion] Option for a Alternative Starvation Tracker
The default Starvation Tracker is based off the outline for your Max Hunger which goes from Green to Yellow to Orange to Red, etc. Or if you define two custom colors for it, such as white to dark red, etc. 

I was wondering if there could be a option for tracking the Starvation Tracker differently, something like this in this image...

When you take starve damage... a dark red outline begins to overlay the hunger bar. Based in the above image this is if the 'starvation frequency loss' is set at 6.

No starve damage, no outline, aka you just ran out of hunger, so it's empty
1st starve damage, 2 hunger icons with have a dark red outline
2nd hit will be 4 icons
3rd hit will be 6 icons
4th hit will be 8 icons
5th hit would be all 10 icons

At this point the 6th starve damage will clear the outline and your max hunger drops, making it require another 6 starve damage before losing max hunger again, in which the hunger bar starts filling up again with the outline. No matter the starvation frequency loss... if you're 1 starve damage away from losing max hunger the hunger bar will always be completely outlined with a dark red color. If the starvation frequency loss was set at 1... then the hunger bar will always have a dark red outline as it's a warning that your next starve damage at that point will reduce max hunger.

The outline can use the textures that are used for the Saturation Outline although the REVERSE saturation outline might look off when the hunger bar shakes. The image is based with the Overlay Style being set at DEFAULT. The textures that are used will depend on what the starvation frequency loss is set at.

While I did mention the color for the starve outline to be a dark red. It could be configurable if one want's to change it's color. I think the dark red color via hex values is... AA0000? Or was it 550000? If going with a default color option.

### LINKED ISSUE #47: ADVANCED Info saturation gain for always edible foods
Best described with an example. When at full hunger, holding something like a golden apple doesn't show how much saturation gets restored in spite of the fact that it is still edible and will restore saturation.

### LINKED ISSUE #54: [Suggestion] Configurable Saturation Cap?
Saturation is tied to your max hunger value, meaning if you have 100 hunger... you can also have 100 Saturation, meaning you have 200 actual hunger, effectively doubling your hunger in a way.

I wonder if there could be a way to config the saturation to these examples. Saturation will never go above these values.

***Examples***
Saturation Scaling: MAX HUNGER
Saturation Cap: 0

Max Hunger: 20
Saturation Limit: 0

Max Hunger: 62
Saturation Limit: 0

Max Hunger: 100
Saturation Limit: 0

-----

Saturation Scaling: HALF MAX HUNGER
Saturation Cap: -1

Max Hunger: 20
Saturation Limit: 10

Max Hunger: 70
Saturation Limit: 35

Max Hunger: 100
Saturation Limit: 50

-----

Saturation Scaling: QUARTER MAX HUNGER
Saturation Cap: 16

Max Hunger: 20
Saturation Limit: 5

Max Hunger: 56
Saturation Limit: 14

Max Hunger: 100
Saturation Limit: 16

=====

Hopefully I explained this well. I dunno if there could also be a overflow of saturation to go slightly beyond the cap, unless the mod Saturation Overflow works with Scaling Feast. I'll give that a check right quick.

*Note*
Each time exhaustion builds up fully... it takes away 1 saturation/hunger so even if you had 0.8 saturation or something... it would be treated as 1 saturation.

*EDIT*
Apparently Saturation overflow does appear to work, but the hud values from scaling feast won't update to show the overflow. The same thing occurs when viewing the Debug Info via F3 when you have Appleskin installed with or without Scaling Feast.

### LINKED ISSUE #56: A way to make the Famine enchantment act instantly
I would like it if there was an option that allowed for the Famine enchantment to directly subtract from your food and saturation points (or add lots of exhaustion all at once) instead of going through the Hunger effect. Doing it that way would allow very high Famine enchantments to be more effective over shorter periods of time, increasing both the risk and reward and encouraging you to get more food points just in case of the rare mob with the very-high Famine level.

With the instant famine disabled, the Famine enchantment can only drain a maximum of 1.25 food points from a player per second, regardless of the enchantment level, and is ineffective if the player already has a Hunger effect level above 50.

With the instant famine enabled, the Famine enchantment drains 1.25 food points instantly (5.0 exhaustion) on every hit, per level of Famine. This can peak as high as 6 to 12 food points per second for Famine V.

### LINKED ISSUE #58: [Suggestion] Gluttony should affect health restored from eating an Iron Apple
**Mod Version**: 1.3.3
**Minecraft Version**: 1.12.2
**Loaded Mods**: (Reproducible with just Scaling Feast)

**Describe the bug**
Eating an (Enchanted) Iron Apple does not give you more health even when you have the Gluttony enchantment. Since Iron Apples are supposed to act like Golden Apples but in reverse, this is inconsistent.

**Steps to Reproduce**
1. Obtain any chestplate and a Iron Apple.
2. Enchant the chestplate with Gluttony level 3.
3. Have 10 HP or less. This allows the full effect of the Iron Apple to take place with Gluttony 3.
4. Eat the Iron Apple.
5. You should gain 2.5 * 4 = 10 HP, but you only get 4 HP as if you didn't have Gluttony.

**Expected behavior**
Having the Gluttony enchantment should increase the health you get for eating an Iron Apple, just like how it increases the hunger you get for eating a Golden Apple.

### PR DESCRIPTION
**Pull request by yeelp**
Changes for 1.4.0

- [x] Closes #45 
- [x] Closes #47 
- [x] Closes #54 
- [x] Closes #56 
- [x] Closes #58 
 
- [x] Debug #45 
- [x] Debug #47 
- [x] Debug #54 
- [x] Debug #56 
- [x] Debug #58 

- [x] Review changes

### CODE REVIEW

File: src/main/java/yeelp/scalingfeast/handlers/EnchantmentHandler.java [hunk 1]
```diff
@@ -49,15 +50,16 @@ public void onAttackEvent(LivingAttackEvent evt)
...
 				{
-					entity.addPotionEffect(new PotionEffect(MobEffects.HUNGER, hduration, 50));
+					int wlevel = (level < 3 ? 0 : 1);
+					entity.addPotionEffect(new PotionEffect(MobEffects.WEAKNESS, 15*20,  wlevel));
 				}
-				entity.addPotionEffect(new PotionEffect(MobEffects.WEAKNESS, 15*20,  wlevel));
+				else
+				{
+					EntityPlayer player = (EntityPlayer) entity;
+					HungerDamage.damageFoodStats(player, 2.25f*level);
```
Comment (James103) [inline src/main/java/yeelp/scalingfeast/handlers/EnchantmentHandler.java:61]: The Hunger effect deducts 1 food point (a combination of hunger and saturation) from players every 40 seconds at level 1 (4.0 max exhaustion / 0.005 exhaustion per tick * 20 ticks per second). Higher levels scale proportionally.

At Hunger level 50, the Hunger effect deducts 1.25 food points from players per second. The Famine enchantment applies that effect level of the Hunger effect for 1 second per enchantment level, deducting 1.25 food points in the process.

The code you've implemented here deducts **2.25** food points from players per hit per enchantment level (since `HungerDamage.damageFoodStats` deducts the number given in food points). This is 1.00 food points **more** than the 1.25 food points per enchantment level I've calculated earlier. Why is it that way?

Comment (yeelp) [reply src/main/java/yeelp/scalingfeast/handlers/EnchantmentHandler.java:61]: This isn't necessarily final, but it was something I wanted to experiment with. The loss in hunger isn't instantaneous, as the game will deduct 1 hunger/saturation per tick while the player's exhaustion >= max exhaustion (which is by default 4.0), which is how it's done here.

In addition, I want to check to see if it's possible for Famine to only activate on full swings (so the player can't spam click). So the 2.25 was also done preemptively to compensate for this, as the windup time for swings and the way hunger will deplete hard caps the amount of hunger you can drain per second.

I hadn't gotten around to testing it yet so I'm not sure how all these dynamics play out yet.

**Comment by James103** [comment]
You have a lot of commits (23) in this PR, some of which could be grouped into just one commit. Have you considered squashing together some of the smaller commits into one for better organization of history?

**Comment by yeelp** [comment]
You're right. Might be a good idea to do that.

**Comment by James103** [comment]
Do you know how to squash and change commits, force-push, etc? These techniques are important for managing your commit history, such as here when you need to group a lot of commits together into one.

**Comment by yeelp** [comment]
It's not something I've done before, but It's also not something I can't learn. I've squashed some of the smaller commits to bring me to 17 total commits, which I'm happy with, but I don't care much about changing the commit history in any other way right now.

**Comment by James103** [comment]
Since you've over a week ahead of schedule, would it be possible to release "Scaling Feast v1.4.0-**beta**" so players can test the new features while you work on the rest of the features that will make it into the final 1.4.0 release?

**Comment by yeelp** [comment]
You're right, probably a good idea. Basically exactly what I thought after I merged.
